### ISSUE TITLE
Cursor is missing

### ISSUE THREAD

**Issue by GabrielUlici** [squizlabs/atom-innerspace#5]
When activating the plugin the cursor on the row is not shown. Not even when you start to write, you see only the letters appear.

**Comment by kharlamov** [comment]
I have the same issue, I thought it was because I was running it with the vim plugin, would be nice to get this fixed.

That being said atom has this built in now, its called "Show Invisibles", you can find it in settings, and change the default characters, I set my new line to an empty space so it wouldn't show it.

**Comment by sertand** [comment]
I had to unpublish this plugin as there is no way to fix the issue due to the changes that have been made in Atom v1.1.0. It is good that Atom has this feature built in.

**Comment by gsherwood** [comment]
> It is good that Atom has this feature built in.

I can't see this feature in Atom. @kharlamov Show Invisibles only supports leading and trailing whitespace, not whitespace between characters.
